08-Apr-20 19:47:25 - 17
08-Apr-20 19:47:25 - Can't create directory /home/fisher/tests/www-python-org_files
08-Apr-20 20:25:19 - Traceback (most recent call last):
  File "/home/fisher/python-project-lvl3/page_loader/page_loader.py", line 33, in page_loader
    os.mkdir(full_dir_name)
FileExistsError: [Errno 17] File exists: '/home/fisher/tests/www-python-org_files'

08-Apr-20 20:25:19 - Can't create directory /home/fisher/tests/www-python-org_files
08-Apr-20 20:52:17 - Traceback (most recent call last):
  File "/home/fisher/python-project-lvl3/page_loader/page_loader.py", line 33, in page_loader
    os.mkdir(full_dir_name)
FileExistsError: [Errno 17] File exists: '/home/fisher/tests/www-python-org_files'

08-Apr-20 20:52:17 - Can't create directory /home/fisher/tests/www-python-org_files
